# Generated by Django 4.0.6 on 2025-10-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20251012_2222'),
        ('chatbot', '0002_auto_20251022_0028'),
    ]

    operations = [
    ]
